### ISSUE TITLE
Use with github pages

### ISSUE THREAD

**Issue by josecastillolema** [Rolinh/jekyll-remote-markdown#1]
Hi @Rolinh !

Hope to find you well,
first of all let me thank you for the plugin, really helpfull.
Do you happen to know if is it possible to use this plugin with github pages?

Thanks a lot,
Jose

**Comment by rolinh** [comment]
Hi @josecastillolema,

Yes, this should be possible. Actually, when I wrote this plugin it was to use it with github pages for [this website](https://github.com/DevMine/devmine.github.io). I see no reason why this approach wouldn't work today.

**Comment by josecastillolema** [comment]
Hi @Rolinh ,

thanks for the quick answer.
It seems to me that github pages has limited the list of plugins to these: https://pages.github.com/versions/
I have tried over and over to get your plugin working (without success :/) using all the three methods suggested in: https://jekyllrb.com/docs/plugins/installation/,
however, every time the build failed with a message like: `The tag remote_markdown is not a recognized Liquid tag`

**Comment by rolinh** [comment]
Yes, this is why I used the method described in [this README](https://github.com/DevMine/devmine.github.io/blob/source/README.md) so that you can use whichever plugin you want at the expense of having to pre-build the static website yourself.

**Comment by josecastillolema** [comment]
thanks for sharing!
